spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://218.48.70.12:3306/dmc_report?autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: dmcmedia
    password: dk#007Gek
    jooq:
      sql-dialect: mysql
